/**
 * CloseIcon component.
 *
 * This component renders an SVG icon representing a close (X) symbol.
 * It is designed to be customizable via props for class names and stroke color.
 *
 * **Note:** This component is pulled from Builder.io. 
 * Do not edit this file directly. Make changes in Builder.io instead.
 *
 * @component
 * @param {CloseIconProps} props - The properties for the CloseIcon component.
 * @param {string} [props.className] - Additional class names to apply to the SVG element.
 * @param {string} [props.strokeColor="#0E1115"] - The color of the stroke for the SVG paths.
 * @returns {React.ReactElement} The rendered CloseIcon component.
 */
"use client";

import * as React from "react";

interface CloseIconProps {
  className?: string;
  strokeColor?: string;
}

const CloseIcon: React.FC<CloseIconProps> = ({
  className = "",
  strokeColor = "#0E1115",
}) => {
  return (
    <svg
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={`close-icon ${className}`}
      style={{ width: "24px", height: "24px", flexShrink: 0 }}
    >
      <path
        d="M4 4L20 20M20 4L4 20"
        stroke={strokeColor}
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
};

export default CloseIcon;
