'use client'
import Image from 'next/image';
import { robotoCondensed } from '@/app/fonts'
import styles from '../page.module.scss'

// Tailwind class objects
const container = 'w-full flex flex-col items-center';
const innerContainer = 'flex flex-col px-4 lg:px-20 text-lg container';
const header = 'flex flex-col w-full mt-4 mb-4 lg:mt-16 lg:mb-16';
const mainTitle = `text-6xl font-bold mb-2 uppercase ${robotoCondensed.className}`;
const section = 'flex flex-col lg:flex-row lg:items-start w-full mb-8 lg:mb-16';
const image = 'mb-4 lg:mr-8 rounded-lg w-[100%] lg:max-w-[50%] object-contain aspect-auto';
const sectionTitle = `text-4xl font-bold mb-2 uppercase ${robotoCondensed.className}`;
const paragraph = 'md:text-base lg:text-xl';

export default function VibePrototype() {
    return (
        <div className={container}>
            <div className={innerContainer}>
                <header className={header}>
                    <h2 className={mainTitle}>Vibe Prototype</h2>
                    <p>
                        <span className="me-4"><b>Role</b>: Prompt Engineer</span>
                        <b>Toolkit</b>: NPM, Next JS, Cody AI, Copilot, Cline
                    </p>
                </header>
                <section className={section}>
                    <Image
                        className={image}
                        src='/images/vibe-prototype/VibePrototypeLogin@2x.webp'
                        alt='Login interface of the Vibe Prototype'
                        width={800}
                        height={600}
                    />
                    <article>
                        <h2 className={sectionTitle}>Overview</h2>
                        <p className={paragraph}>
                            This is a Next.js project bootstrapped with create-next-app and Google Material UI. All files, UI, and functionality was generated by AI prompts, using a combination of CodyAI, Copilot, and Cline.
                        </p>
                        <p className={paragraph}>
                            The Data Assistant chatbot is a simple implementation of a chat interface, where users can ask questions and receive answers. The chatbot uses the OpenAI API to generate responses based on the user&apos;s input. Model used: GPT-3.5-turbo.
                        </p>

                    </article>

                </section>
                <section className={section}>
                    <a href='https://github.com/JFlo76/PrototypeTest' target='blank' className={`block lg:inline-block text-center lg:text-left ${styles.linkTo_work} ${robotoCondensed.className} uppercase`}>View Github Project</a>
                </section>
                <section className={section}>
                    <Image
                        className='mb-4 rounded-lg w-[100%] object-contain aspect-auto'
                        src='/images/vibe-prototype/VibePrototypeDashboard@2x.webp'
                        alt='Dashboard interface of the Vibe Prototype'
                        width={1200}
                        height={600}
                    />

                </section>
            </div>
        </div>
    )
}